import fs from'node:fs';import vm from'node:vm';
const H={},on=(n,f)=>(H[n]??=[]).push(f),ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),canvas={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f)=>on('c:'+n,f)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{},document:{getElementById:()=>canvas,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f)=>on(n,f),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','hud12.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box);
e('startLevel(1);LM.slice(0,-1).forEach(l=>l.os.forEach(o=>o.hp=0));waveUp(2);waveUp(3)');let hp=e('LM[4].os[0].hp');e('hitObj(unis[0],LM[4].os[0],999)');if(e('LM[4].os[0].hp')!==hp||!e("msg.includes('28% CHAOS')"))throw Error('Town Hall chaos gate');
e("painted=PW*PH*.4;var o=LM[4].os[0];for(let q of unis){q.x=q.y=0}unis[0].x=o.x+o.w/2;unis[0].y=o.y+o.h/2;unis[1].x=o.x+o.w/2+20;unis[1].y=o.y+o.h/2;hitObj(unis[0],o,999)");if(e('LM[4].os[0].hp')!==hp||!e("msg.includes('RALLY 2/3')"))throw Error('Town Hall three-unicorn rally gate');
e("var o=LM[4].os[0];unis[3].x=o.x+o.w/2-20;unis[3].y=o.y+o.h/2;hitObj(unis[0],o,999)");if(!e('hallDone()')||e('landWin')||e('cleaners.length')!==6||!e("lmText.includes('FINAL CLEANUP')"))throw Error('Hall must open final color phase, not instant victory');if(Math.abs(e('stageGoal')-.5)>.001||Math.abs(e('distGoal')-.29)>.001)throw Error('Prisborough coverage target');
e('timeLeft=30;painted=PW*PH*.51;dmask|=15;update(.01)');if(!e('landWin')||e('victoryT')<2)throw Error('coverage + four secured districts should start takeover hold');
e('painted=PW*PH*.49;update(.01)');if(e('landWin')||e('victoryT')||((e('dmask')&15)!==15))throw Error('cleanup below target must break hold without erasing district checkpoints');
e('timeLeft=75;painted=PW*PH*.08;townDamage=townMax*.16;chains=0');let low=e('comp()');if(low>=1e5||e(`tier(${low})`)!=='LOW')throw Error('minimal conquest must remain low tier');
e('landWin=1;timeLeft=45;painted=PW*PH*.55;townDamage=townMax*.58;chains=4');let high=e('comp()');if(high<=low*2||!['HIGH','HIGHER','HIGHEST'].includes(e(`tier(${high})`)))throw Error('completed skillful takeover must clearly outrank failed conquest');
e("landWin=1;state='end';startLevel(1)");if(e('zone')!==1||e('timeLeft')!==112||e('cleaners.length')!==2||Math.abs(e('stageGoal')-.53)>.001)throw Error('Washwater cleanup + coverage progression');
e("landWin=1;state='end';startLevel(1)");if(e('zone')!==2||e('timeLeft')!==108||Math.abs(e('stageGoal')-.56)>.001)throw Error('Cloudtop progression');
e("S.s('ccC2',1);state='end';landWin=1;startLevel(1)");if(!e('plus')||e('zone')!==0||e('timeLeft')!==114||e('heat')!==0||!e("lmText.includes('HEAT 1/10')")||Math.abs(e('stageGoal')-.56)>.001)throw Error('Stampede+ Heat progression');
e("S.s('ccHeat',9);zone=2;state='play';startLevel(1)");if(Math.abs(e('stageGoal')-.782)>.001||e('distGoal')<.45)throw Error('Heat 10 coverage pressure must materially exceed campaign');e('landWin=1;victoryT=.01;update(.02)');if(e("S.g('ccHeat')")!==9)throw Error('Heat 10 must be mastery cap');
console.log(`competitive v0.28 staged-herd rally smoke: PASS low=${low} skilled=${high}`);
