import fs from'node:fs';import vm from'node:vm';
const H={},on=(n,f,c)=>(H[n]??=[]).push({f,c:!!c}),ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),C={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f,c)=>on('c:'+n,f,c)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{},document:{getElementById:()=>C,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f,c)=>on(n,f,c),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','hud12.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box);
e("S.s('ccIntro16',1);startLevel(1);runTime=100;update(.01)");if(e('wave')!==1||e('unis.filter(u=>u.live).length')!==4)throw Error('elapsed time alone must not grow the herd');
e("var u=unis[0];u.distract=0;for(let o of LM[0].os)hitObj(u,o,9999)");if(e('wave')!==1)throw Error('first outer landmark must not grow herd');
e("var u=unis[0];u.distract=0;for(let o of LM[1].os)hitObj(u,o,9999)");if(e('wave')!==2||e('unis.filter(u=>u.live).length')!==5)throw Error('second outer landmark must release fifth unicorn');
e("var u=unis[0];u.distract=0;for(let o of LM[2].os)hitObj(u,o,9999)");if(e('wave')!==2)throw Error('third outer landmark must keep five-unicorn act');
e("var o=LM[3].os[0],u=unis[0];u.distract=0;u.x=o.x+o.w/2;u.y=o.y+o.h/2;unis[1].x=u.x+20;unis[1].y=u.y;hitObj(u,o,9999)");if(e('wave')!==3||e('unis.filter(u=>u.live).length')!==6)throw Error('fourth outer landmark must release sixth unicorn');
console.log('landmark progression v0.35: PASS 4 → 5 at landmark 2 → 6 at landmark 4; no elapsed-time unlock');
