import fs from'node:fs';import vm from'node:vm';
const H={},on=(n,f,c)=>(H[n]??=[]).push({f,c:!!c}),ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),C={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f,c)=>on('c:'+n,f,c)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{},document:{getElementById:()=>C,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f,c)=>on(n,f,c),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','hud12.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box);
e("S.s('ccIntro16',1);startLevel(1);S.s('ccRun',0)");if(e('defense()')!==1)throw Error('run doctrine must be SNATCH fixture');e('addClean(1);var c=cleaners[0];var u=unis[1];c.x=u.x;c.y=u.y;u.distract=2;msgT=0;updateCleaners(.01)');if(e('u.live')||e('c.u')!==1||!e("msg.includes('CAPTURED')"))throw Error('SNATCH must capture a socially distracted unattended unicorn');e('for(let q of unis)if(q.live){q.x=2500;q.y=1500}unis[0].x=c.x;unis[0].y=c.y;unis[0].dash=1;c.stun=0;updateCleaners(.01)');if(e('c.u')!==1||!e("msg.includes('RESCUE 1/2')"))throw Error('solo attacker may stop but not free capture truck');e('unis[3].x=c.x+80;unis[3].y=c.y;updateCleaners(.01)');if(!e('u.live')||e('c.u')>=0||!e("msg.includes('FREED')")||e('score')<700)throw Error('two-unicorn rescue must free captive and reward recovery');
e("S.s('ccRun',1);c.stun=0;c.u=-1;var b=objs.find(o=>o.t==='b'&&!o.lm);b.hp=0;townDamage=100;c.x=b.x+b.w/2;c.y=b.y+b.h/2;c.spray=.01");let damage=e('townDamage');e('updateCleaners(.05)');if(e('b.hp')<=0||e('townDamage')>=damage||!e("msg.includes('REBUILT')"))throw Error('REBUILD doctrine must resurrect destroyed ordinary structures and undo destruction pressure');
e("S.s('ccRun',2);c.spray=.01;c.stun=0");e('updateCleaners(.05)');if(e('c.spray')>.16)throw Error('SWEEP doctrine must reset to a materially faster cleanup cadence');
e("S.s('ccRun',0);wave=1");let a=e('defense()');e('wave=2');let b=e('defense()');e('wave=3');let d=e('defense()');if(new Set([a,b,d]).size!==3)throw Error('each run must rotate through all three town doctrines');
e("startLevel(1);S.s('ccRun',0);wave=1;for(let q of unis){q.live=1;q.distract=0}cleaners=[];addClean(3);for(let i=0;i<3;i++){msgT=0;let q=unis.find(q=>q.live);q.distract=2;cleaners[i].x=q.x;cleaners[i].y=q.y;updateCleaners(.01)}");if(e('cleaners.filter(c=>c.u>=0).length')!==3)throw Error('SNATCH must permit three concurrent prisoners');e('update(.01)');if(e('landWin')>=0||e('victoryT')<=0||!e("msg.includes('HERD COLLAPSE')"))throw Error('third capture must trigger irreversible herd collapse');e('victoryT=.01;update(.02)');if(e("state")!=='end')throw Error('herd collapse must end the run');
e("startLevel(1);timeLeft=.01;state='play';update(.1)");if(e("state")!=='play')throw Error('timer must not end a v0.32 run');
console.log('town response v0.32: PASS rescue + multi-capture + 3-capture collapse + rebuild + sweep + no timer loss');
