import fs from'node:fs';import vm from'node:vm';
const H={},rects=[],on=(n,f,c)=>(H[n]??=[]).push({f,c:!!c}),ctx=new Proxy({fillStyle:'#000',fillRect(x,y,w,h){rects.push([this.fillStyle,x,y,w,h])},createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),C={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f,c)=>on('c:'+n,f,c)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{ccZone:1,ccIntro16:1},document:{getElementById:()=>C,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f,c)=>on(n,f,c),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box),eq=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(m+'\n'+JSON.stringify(a)+'\n!=\n'+JSON.stringify(b))};
e('startLevel(1)');
const bay=[[640,0,180,1800],[1420,0,180,1800],[2480,0,180,1800],[0,460,3200,190],[0,1230,3200,190],[1580,960,1620,90]];eq(e('roads'),bay,'Washwater road graph moved');
if(e("objs.some(o=>o.t==='hedge')"))throw Error('Washwater must remove hedge barriers for open harbor lanes');
if(e('LM.length')!==5||!e('LM.every(l=>l.os.every(o=>objs.includes(o)))'))throw Error('all five landmarks must survive harbor transform');
if(!e('ups.some(p=>p.x>1580&&p.y>960&&p.y<1050)'))throw Error('harbor connector must expose a powerup decision');
if(!e('objs.every(o=>o.x>=260)'))throw Error('western waterfront must remain structurally clear');
if(e("(()=>{let r=roads[5];return objs.some(o=>o.t==='b'&&o.x<r[0]+r[2]&&o.x+o.w>r[0]&&o.y<r[1]+r[3]&&o.y+o.h>r[1])})()"))throw Error('generic building overlaps harbor connector');
const before=e("JSON.stringify([objs.map(o=>[o.x,o.y,o.w,o.h,o.hp]),roads,ups.map(p=>[p.x,p.y]),flowers.map(f=>[f.x,f.y]),unis.map(u=>[u.x,u.y])])");rects.length=0;e('world()');const after=e("JSON.stringify([objs.map(o=>[o.x,o.y,o.w,o.h,o.hp]),roads,ups.map(p=>[p.x,p.y]),flowers.map(f=>[f.x,f.y]),unis.map(u=>[u.x,u.y])])");if(before!==after)throw Error('Washwater rendering mutated gameplay state');
if(!rects.some(r=>r[0]==='#74889a'&&r[1]===0&&r[2]===0&&r[3]===3200&&r[4]===1800))throw Error('Washwater blue-gray ground missing');
if(!rects.some(r=>r[0]==='#567f8c'&&r[1]===0&&r[2]===0&&r[3]===160&&r[4]===1800))throw Error('western harbor water band missing');
for(let x of [640,1420,2480])for(let y of [460,1230]){let n=rects.filter(r=>r[3]===18&&r[4]===58&&r[1]>=x+10&&r[1]<=x+146&&(r[2]===y+8||r[2]===y+124)).length;if(n!==10)throw Error(`crosswalk mismatch at ${x},${y}: ${n}`)}
e('zone=0;startLevel(1)');eq(e('roads'),[[760,0,180,1800],[1540,0,180,1800],[2320,0,180,1800],[0,540,3200,190],[0,1130,3200,190]],'Prismborough road graph changed');if(e("objs.filter(o=>o.t==='hedge').length")!==6)throw Error('Prismborough hedge contract changed');rects.length=0;e('world()');if(!rects.some(r=>r[0]==='#78986d'&&r[3]===3200&&r[4]===1800))throw Error('Prismborough ground changed');
console.log('Washwater Bay harbor: PASS roads=6 openHedges=0 landmarks=5 connectorPowerup=1 waterfrontClear=1 crosswalks=60 renderPure=1 baseWorldUnchanged=1');
