import fs from'node:fs';import vm from'node:vm';
const H={},rects=[],on=(n,f,c)=>(H[n]??=[]).push({f,c:!!c}),ctx=new Proxy({fillStyle:'#000',fillRect(x,y,w,h){rects.push([this.fillStyle,x,y,w,h])},createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),C={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f,c)=>on('c:'+n,f,c)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{ccZone:1,ccIntro16:1},document:{getElementById:()=>C,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f,c)=>on(n,f,c),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box),eq=(a,b,m)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(m+'\n'+JSON.stringify(a)+'\n!=\n'+JSON.stringify(b))},near=(a,b)=>Math.abs(a-b)<1e-6;
e('startLevel(1)');
const bay=e('roads');if(bay.length!==5||!near(bay[0][0],843.2)||!near(bay[1][0],1602.8)||!near(bay[2][0],2342.4)||!near(bay[3][1],516.8)||!near(bay[4][1],1129.6))throw Error('Washwater authored road spacing moved: '+JSON.stringify(bay));
if(e("objs.some(o=>o.t==='hedge')"))throw Error('Washwater must remove hedge barriers for open harbor lanes');
if(e('LM.length')!==5||!e('LM.every(l=>l.os.every(o=>objs.includes(o)))'))throw Error('all five landmarks must survive harbor remap');
if(!e('ups.some(p=>p.x<600)&&ups.some(p=>p.x>2800)&&ups.some(p=>p.x>1750&&p.x<2100&&p.y>800&&p.y<1100)'))throw Error('powerups must span waterfront, harbor center and far shore');
if(!e('objs.every(o=>o.x>240)'))throw Error('western waterfront must remain structurally clear');
if(e("(()=>{let b=objs.filter(o=>o.t==='b');for(let i=b.length;i--;)for(let j=i;j--;)if(b[i].x<b[j].x+b[j].w&&b[i].x+b[i].w>b[j].x&&b[i].y<b[j].y+b[j].h&&b[i].y+b[i].h>b[j].y)return 1;return 0})()"))throw Error('harbor remap collapsed building lots');
if(e("(()=>{for(let o of objs)if(o.t==='b')for(let r of roads)if(o.x<r[0]+r[2]&&o.x+o.w>r[0]&&o.y<r[1]+r[3]&&o.y+o.h>r[1])return 1;return 0})()"))throw Error('harbor remap introduced building/road overlap');
if(e("msg")!=='HARBOR DISTRICT • OPEN LANES')throw Error('Washwater launch framing missing');
const before=e("JSON.stringify([objs.map(o=>[o.x,o.y,o.w,o.h,o.hp]),roads,ups.map(p=>[p.x,p.y]),flowers.map(f=>[f.x,f.y]),unis.map(u=>[u.x,u.y,u.tx,u.ty])])");rects.length=0;e('world()');const after=e("JSON.stringify([objs.map(o=>[o.x,o.y,o.w,o.h,o.hp]),roads,ups.map(p=>[p.x,p.y]),flowers.map(f=>[f.x,f.y]),unis.map(u=>[u.x,u.y,u.tx,u.ty])])");if(before!==after)throw Error('Washwater rendering mutated gameplay state');
if(!rects.some(r=>r[0]==='#74889a'&&r[1]===0&&r[2]===0&&r[3]===3200&&r[4]===1800))throw Error('Washwater blue-gray ground missing');
if(!rects.some(r=>r[0]==='#567f8c'&&r[1]===0&&r[2]===0&&r[3]===160&&r[4]===1800))throw Error('western harbor water band missing');
if(rects.filter(r=>r[0]==='rgba(245,240,220,.72)'&&r[3]===18&&r[4]===58).length!==60)throw Error('Washwater must retain 60 derived crosswalk stripes');
e('zone=0;startLevel(1)');eq(e('roads'),[[760,0,180,1800],[1540,0,180,1800],[2320,0,180,1800],[0,540,3200,190],[0,1130,3200,190]],'Prismborough road graph changed');if(e("objs.filter(o=>o.t==='hedge').length")!==6)throw Error('Prismborough hedge contract changed');rects.length=0;e('world()');if(!rects.some(r=>r[0]==='#78986d'&&r[3]===3200&&r[4]===1800))throw Error('Prismborough ground changed');
console.log('Washwater Bay harbor: PASS roads=5 asymmetric=1 openHedges=0 landmarks=5 powerupSpan=1 waterfrontClear=1 crosswalks=60 renderPure=1 baseWorldUnchanged=1');
