let plus=!!S.g('ccC2'),heat=S.g('ccHeat'),mode=S.g('ccMode')%4;
/* PRISM GATE retired: its bytes now fund the takeover mastery loop. */
const DI=['NORMAL','MEDIUM','HARD','IMPOSSIBLE'],DR=['SWEEP','SNATCH','REBUILD'],chaos=()=>.28+mode*.025+(plus?Math.min(heat,8)*.01:0);
function objective(){let n=LM.slice(0,-1).filter(lmDone).length,p;if(n<4)return'BREAK '+n+'/4';if(!hallDone()){p=takeover();if(p<chaos())return'CHAOS '+(p*100|0)+'/'+(chaos()*100|0)+'%';return'RALLY '+(3+(mode>0)+(mode>2))+' • HALL'}if(cleaners.some(c=>c.u>=0))return'RESCUE HERD';p=paintPct();if((dmask&15)<15)return'SECURE 4 DISTRICTS';if(p<stageGoal)return'COLOR '+(p*100|0)+'/'+(stageGoal*100|0)+'%';return'HOLD THE TOWN'}
function comp(){let m=[1,1.12,1.25][zone]*(plus?1.12+Math.min(heat,9)*.04:1);return Math.round(((landWin>0?4e4:0)+paintPct()*9e4+structPct()*7e4+Math.min(chains,6)*6e3)*m)}
function tier(n=comp()){return n<1e5?'LOW':n<15e4?'MEDIUM':n<22e4?'HIGH':n<3e5?'HIGHER':'HIGHEST'}
const _plusStart=startLevel;startLevel=function(n){_plusStart(n);plus=!!S.g('ccC2');heat=S.g('ccHeat');mode=S.g('ccMode')%4;stageGoal=.5+zone*.03+mode*.04+plus*(.06+Math.min(heat,9)*.018);distGoal=stageGoal*.58;if(n){let q=1+mode*.22;for(let o of objs)if(o.hp<999)o.hp=o.max*=q;if(mode)ups=ups.filter((p,i)=>!(i%(mode+1)));for(let c of cars)c.v*=1+mode*.09;unis[2].live=unis[4].live=0;lmText=DI[mode]+' • '+DR[defense()]+' • HERD 4/6';lmTextT=2}if(n&&plus){let h=Math.min(heat,9);addClean(1+(h>3)+(mode>1));for(let c of cars)c.v*=1.08+h*.02;lmText='HEAT '+(h+1)+'/10 • '+DI[mode]+' • HERD 4/6';lmTextT=2}};
const _plusWave=waveUp;waveUp=function(w){if(level&&(w===2&&LM.filter(lmDone).length<2||w===3&&!outerDone()))return;_plusWave(w);if(level){msg=w===2?'COMET JOINS':'BUMPER!';msgT=2;lmText=DR[defense()]+' • '+(w===2?'HERD 5/6':'HERD 6/6');lmTextT=2}};
const _plusHit=hitObj;hitObj=function(u,o,d){if(level&&u.distract>1.1)return msg='BICKER!',msgT=1;if(o&&o.lm==='hall'&&outerDone()&&takeover()<chaos()){msg='NEED '+(chaos()*100|0)+'% CHAOS';msgT=1;return}if(o&&(o.lm==='clock'||o.lm==='hall'&&outerDone())){let h=o.lm==='hall',k=h?3+(mode>0)+(mode>2):2+(mode>1),n=unis.filter(q=>q.live&&Math.hypot(q.x-o.x-o.w/2,q.y-o.y-o.h/2)<320+mode*20).length;if(n<k){msg='RALLY '+n+'/'+k;msgT=1;return}}_plusHit(u,o,d)};
const _plusBoom=landmarkBoom;landmarkBoom=function(l,u){_plusBoom(l,u);if(level&&l.k!=='hall'){if(cleaners.length<9+mode)addClean(1+(mode>1))}if(level&&l.k==='hall'){landWin=victoryT=0;addClean(2+(heat>5)+(mode>0)+(mode>2));lmText='FINAL CLEANUP • COLOR '+(stageGoal*100|0)+'%';lmTextT=2}};
const _plusZone=updateZone;updateZone=function(dt){_plusZone(dt);if(level&&plus&&zone!==2)for(let u of unis)if(u.live)u.vx+=Math.sin(clock*.7)*(45+heat*6+mode*10)*dt};
const _plusUpdate=update;update=function(dt){let b=state;if(b==='play'&&level&&hallDone()&&landWin>=0&&landWin<2){let q=paintPct()>=stageGoal&&(dmask&15)===15&&!cleaners.some(c=>c.u>=0);if(!q)landWin=victoryT=0;else if(!victoryT)landWin=1,victoryT=2.5;else if(victoryT<=dt){landWin=2;victoryT=2;fx(WW/2,WH*.82,60,420);shake=28;flash=1;for(let i=6;i--;)PX.fillStyle=`hsl(${i*60} 95% 60%)`,PX.fillRect(i*PW/6,0,PW/6,PH);cleaners=[]}}if(level)for(let u of unis)if(u.live){u.paint+=dt*(wave-1+mode/2)/3;if(u.id!==caps[0]&&unis.some(q=>q.live&&q!==u&&Math.hypot(q.x-u.x,q.y-u.y)<260+mode*20))u.distract=2}if(level)timeLeft=99;_plusUpdate(dt);if(b==='play'&&state==='end'&&landWin>0&&plus&&heat<9)S.s('ccHeat',++heat)};
addEventListener('keydown',e=>{if(state==='end'){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Enter'&&!e.repeat)state='title',objs=[]}else if(state==='title'&&S.g('ccIntro16')&&e.code==='KeyM')e.stopImmediatePropagation(),S.s('ccMode',mode=(mode+1)%4)},true);C.addEventListener('mousedown',e=>state==='end'&&e.stopImmediatePropagation(),true);
C.onpointerdown=e=>{let r=C.getBoundingClientRect(),s=Math.min(r.width/W,r.height/H);mx=cl((e.clientX-r.left-r.width/2)/s+W/2,0,W);my=cl((e.clientY-r.top-r.height/2)/s+H/2,0,H);AC?.resume?.()};
title=function(){if(guide)return _titleW();if(!objs.length){startLevel(0);state='title';unis=[];caps=[-1,-1];for(let i=5;i--;)objs[i].hue=i*72;for(let i=6;i--;){let x=330+i*108,u=makeUni(i,x,450);u.a=Math.atan2(-147,600-x);unis.push(u)}}world();X.fillStyle='rgba(5,8,15,.78)';X.fillRect(0,0,W,150);X.fillStyle='#fff';text('UNICORN STAMPEDE',W/2,76,52,'center');X.fillStyle='#ffe77d';text('CONTROL THE HERD',W/2,122,20,'center');if(S.g('ccIntro16')){text('A/D • '+ZN[zone],W/2,585,13,'center');X.fillStyle='#ffe56d';text('M • '+DI[mode]+(plus?' • HEAT '+(Math.min(heat,9)+1)+'/10':''),W/2,610,14,'center')}X.fillStyle='#fff';text(S.g('ccIntro16')?'ENTER • PLAY':'ENTER • TRAINING',W/2,650,20,'center');text('C • RULES',W/2,680,13,'center')};
end=function(){let w=landWin>0;X.fillStyle='#05080f88';X.fillRect(0,0,W,H);X.fillStyle=w?'#77efa2':'#ff829f';text(w?'TOWN CONQUERED':'HERD COLLAPSED',W/2,180,44,'center');X.fillStyle='#fff';text('SCORE '+(score|0),W/2,260,30,'center');text(w?DI[mode]+' • '+(paintPct()*100|0)+'%':'3 CAPTURED',W/2,310,16,'center');text('ENTER • MENU',W/2,610,18,'center')};