let LM=[],cleaners=[],lmText='',lmTextT=0,victoryT=0,beatT=0,beatN=0,landWin=0,stamp=0;
const lmDone=l=>l&&l.os.every(o=>o.hp<=0),outerDone=()=>LM.length>1&&LM.slice(0,-1).every(lmDone),hallDone=()=>LM.length&&lmDone(LM[LM.length-1]),defense=()=> (S.g('ccRun')+wave)%3;
function pickObj(x,y,used=[]){let q,bd=1e9;for(let o of objs)if(o.t==='b'&&!used.includes(o)){let d=Math.hypot(o.x+o.w/2-x,o.y+o.h/2-y);if(d<bd){bd=d;q=o}}return q}
function markLand(k,n,os,m=1){os=os.filter(Boolean);let l={k,n,os};for(let o of os){o.lm=k;o.ln=n;o.max=o.hp*=m}LM.push(l);return l}
function setupLandmarks(n){LM=[];if(!n){let b=pickObj(1030,120);if(b){b.hue=8;markLand('bakery','BAKERY',[b],.5)}return}let used=[],bak=pickObj(430+R(360,-140),300+R(250,-100),used);used.push(bak);let green=pickObj(2750+R(180,-450),320+R(260,-100),used);used.push(green);let hall=pickObj(1630+R(450,-450),1480+R(140,-180),used);used.push(hall);if(bak)bak.hue=8;if(green)green.hue=310;if(hall)hall.hue=85;markLand('bakery','BAKERY',[bak],1.35);let stalls=objs.filter(o=>o.t==='stall');markLand('market','MARKET',stalls,1.35);markLand('green','GREENHOUSE',[green],1.45);let clockObj=objs.find(o=>o.t==='clock');markLand('clock','CLOCK TOWER',[clockObj],1.25);markLand('hall','TOWN HALL',[hall],1.65)}
const _startLevel=startLevel;startLevel=function(n){_startLevel(n);cleaners=[];lmTextT=victoryT=beatT=beatN=landWin=stamp=0;setupLandmarks(n);if(!n)stageGoal=.95};
const _hitObj=hitObj;hitObj=function(u,o,d){if(o&&o.lm==='hall'&&!outerDone()){if(msgT<.15){msg='TOWN HALL SHIELDED';msgT=.8;tone(150,.08,'square',.018,90)}return}let before=o&&o.hp;_hitObj(u,o,d);if(o&&o.lm&&before>0&&o.hp<=0){let l=LM.find(x=>x.k===o.lm);if(l&&lmDone(l))landmarkBoom(l,u)}};
function landmarkBoom(l,u){let o=l.os[0],x=l.os.reduce((a,q)=>a+q.x+q.w/2,0)/l.os.length,y=l.os.reduce((a,q)=>a+q.y+q.h/2,0)/l.os.length;score+=l.k==='hall'?6500:3000;paintStamp(u,x,y,l.k==='hall'?270:150);fx(x,y,l.k==='hall'?46:26,240);shake=18;flash=.8;lmText=l.k==='hall'?'TOWN HALL SMASHED!':l.n+' SMASHED • '+LM.slice(0,-1).filter(lmDone).length+'/4';lmTextT=2;tone(l.k==='clock'?660:220,.35,'triangle',.055,880);if(l.k==='green')for(let i=0;i<14;i++)flies.push({x:x+R(120,-120),y:y+R(90,-90),a:R(T),s:R(2,.8)});if(l.k==='market'&&mode<3){addUp('rage',x,y);if(!mode)addUp('bomb',x+70,y)}if(l.k==='clock')for(let q of unis)q.anger=cl(q.anger+.22,0,1);if(l.k==='hall')for(let q of unis){q.frenzy=Math.max(q.frenzy,4);q.anger=1}}
function eraseStamp(x,y,r){let cx=x/PS,cy=y/PS,rr=r/PS,x0=Math.max(0,Math.floor(cx-rr)),x1=Math.min(PW-1,Math.ceil(cx+rr)),y0=Math.max(0,Math.floor(cy-rr)),y1=Math.min(PH-1,Math.ceil(cy+rr)),r2=rr*rr,n=0;for(let yy=y0;yy<=y1;yy++)for(let xx=x0;xx<=x1;xx++){let dx=xx+.5-cx,dy=yy+.5-cy;if(dx*dx+dy*dy<=r2){let k=yy*PW+xx;if(PM[k]){PM[k]=0;painted--;dpaint[(xx<PW/2?0:1)+(yy<PH/2?0:2)]--;n++}}}if(n){PX.save();PX.globalCompositeOperation='destination-out';PX.beginPath();PX.arc(cx,cy,rr,0,T);PX.fill();PX.restore()}return n}
function addClean(n){for(let i=0;i<n;i++)cleaners.push({x:i%2?WW-300:300,y:[630,1225,920,1500][cleaners.length%4],v:(i%2?-1:1)*R(190,145)*(1+mode*.12),stun:0,spray:R(.2)})}
function updateCleaners(dt){let d=defense(),p=0;for(let c of cleaners){c.stun=Math.max(0,c.stun-dt);if(!c.stun){if(d===1&&!p&&!(c.u>=0)&&(landWin<0||msgT<.1)){let a=unis.find(q=>q.live&&!q.cap&&q.distract>1.1);if(a){c.y+=cl(a.y-c.y,-(140+mode*40)*dt,(140+mode*40)*dt);if(Math.hypot(a.x-c.x,a.y-c.y)<100&&(landWin<0||unis.filter(q=>q.live).length>3)){c.u=a.id;a.live=0;p=1;msg=a.name+' CAPTURED!';msgT=1.3}}}c.x+=c.v*dt;if(c.x<80||c.x>WW-80)c.v*=-1;c.spray-=dt;if(c.spray<=0){c.spray=((d?.25:.15)-stamp*.015)/(1+mode*.18);eraseStamp(c.x,c.y,46);if(d===2){let o=objs.find(o=>o.t==='b'&&!o.lm&&!o.hp&&Math.hypot(o.x+o.w/2-c.x,o.y+o.h/2-c.y)<180),r=(1+mode/5)/3;if(o)o.hp=o.max*r,townDamage=Math.max(0,townDamage-o.val*r),msg='REBUILT!',msgT=1}}for(let u of unis)if(u.live&&Math.hypot(u.x-c.x,u.y-c.y)<65&&(u.dash||u.frenzy||u.boost)){c.stun=3;score+=180;fx(c.x,c.y,8,120);tone(95,.09,'square',.015,180);c.x=cl(c.x+Math.sign(u.vx||1)*55,50,WW-50)}}if(c.u>=0){let a=unis[c.u];a.x=c.x;a.y=c.y;if(c.stun>2.8&&landWin>=0){let k=unis.filter(q=>q.live&&Math.hypot(q.x-c.x,q.y-c.y)<260-mode*15).length;if(k>1){a.live=1;c.u=-1;score+=700;msg=a.name+' FREED!';msgT=1.3}else msg='RESCUE '+k+'/2',msgT=1}}}}
const _waveUp=waveUp;waveUp=function(w){_waveUp(w);if(level){addClean(2);if(w===3)tone(330,.25,'sawtooth',.035,660)}};
function music(dt){if(!AC||muted||state!=='play'||(beatT-=dt)>0)return;beatT=wave>2?.17:.24;let n=beatN++;if(!(n%4))tone(55,.07,'sine',.018,38);if(stamp>2&&n%2)tone(220+55*(n%4),.04,'triangle',.007)}
const _update=update;update=function(dt){_update(dt);lmTextT=Math.max(0,lmTextT-dt);if(state==='play'&&!paused){stamp=unis.filter(u=>u.live&&(u.order||u.frenzy||u.boost||u.hot)).length;if(level)updateCleaners(dt);if(level&&landWin>=0&&cleaners.filter(c=>c.u>=0).length>2){landWin=-1;victoryT=3;msg='HERD COLLAPSE!';msgT=3;flash=1;shake=18;for(let u of unis)if(u.live)u.stun=u.distract=4;for(let c of cleaners)c.v*=2}music(dt);if(victoryT>0){victoryT-=dt;if(victoryT<=0){if(landWin<0)for(let u of unis)u.live=0;score+=Math.round(paintPct()*8e4+(landWin>0?2e4:0));state='end'}}}};
const _world=world;world=function(){_world();if(!level)return;X.save();X.translate(ox,oy);X.scale(z,z);for(let c of cleaners){X.save();X.translate(c.x,c.y);X.fillStyle=c.stun?'#9aa5b7':'#f4f7fb';rr(-44,-24,88,48,10);X.fillStyle=c.u>=0?`hsl(${hues[c.u]} 95% 58%)`:'#67cce8';X.fillRect(-30,-16,38,22);X.fillStyle='#26394c';X.beginPath();X.arc(-25,26,10,0,T);X.arc(25,26,10,0,T);X.fill();X.fillStyle='#ff5f83';X.fillRect(12,-13,22,8);X.restore()}X.restore()};
