let whip=0,suggested=-1,guide=0,train=!S.g('ccIntro16');
/* YELLOW: CLICK MALLOW RING */
function roadAt(u){if(!u||!PM)return 0;let x=cl(u.x/PS|0,0,PW-1),y=cl(u.y/PS|0,0,PH-1);return PM[y*PW+x]}
const need=q=>q.cool<0?-9:q.distract?12+q.distract:Math.hypot(q.vx,q.vy)<55&&!q.order?9:!roadAt(q)?6:ups.some(p=>p.on&&Math.hypot(p.x-q.x,p.y-q.y)<300)?5:Math.min(4,(q.cool||0)/8);
const _soloStart=startLevel;startLevel=function(n){_soloStart(n);guide=0;suggested=-1;if(!n)ups=[];for(let u of unis)u.power=u.tap=u.tapT=0};
const _soloAI=moveAI;moveAI=function(u,d){let c=caps[1];caps[1]=caps[0];let a=_soloAI(u,d);caps[1]=c;return a};
const _soloDistract=distractForce;distractForce=function(u){let f=_soloDistract(u);if(u!==unis[caps[0]]&&roadAt(u))f[0]*=.55,f[1]*=.55;return f};
cycle=function(){if(state!=='play')return;let o=caps[0],u=unis[o];if(!level&&intro.step===3&&Math.hypot(u.vx,u.vy)<=35)return msg='MOVE + SHIFT TO SEND',msgT=.8;if(Math.hypot(u.vx,u.vy)>35)u.order=roadAt(u)?5.2:4,u.ox=Math.cos(u.a),u.oy=Math.sin(u.a);u.cool=-1;let j=o,b=-10;for(let i=unis.length;i--;){let q=unis[i];if(q.live&&i!==o&&need(q)>=b)b=need(q),j=i}caps[0]=j;u=unis[j];u.order=u.cool=0;u.distract=Math.max(0,u.distract-.2);if(!level){if(intro.step===3&&j!==intro.o)intro.step=4,intro.l=0;else if(intro.step===5&&j===intro.o)intro.step=6,intro.rescue=0}};
function dashSolo(){if(state!=='play')return;let u=unis[caps[0]],n=u.power|0;if(n<2){msg='WHIP 2X → DASH';msgT=.7;return}u.dash=.2+n*.07;let v=570+n*95;u.vx=Math.cos(u.a)*v;u.vy=Math.sin(u.a)*v;paintStamp(u,u.x,u.y,38+n*12);fx(u.x,u.y,6+n*2,120);tone(150+n*35,.1,'sawtooth',.03);u.power=u.tap=u.tapT=0;if(n===5)award('MAX DASH',850);if(!level&&intro.step===2){intro.step=3;msg='SHIFT → SWITCH';msgT=1}}
C.addEventListener('mousedown',e=>{if(state!=='play'||e.button)return;e.preventDefault();e.stopImmediatePropagation();audio();let u=unis[caps[0]],x=(mx-ox)/z,y=(my-oy)/z,d=Math.hypot(x-u.x,y-u.y);if(d>38&&d<180)whip={x,y,i:caps[0],l:.13,hit:0},crackWhip();else msg='CLICK RING',msgT=.5},true);
C.addEventListener('mousedown',e=>{if(state==='title'){e.preventDefault();e.stopImmediatePropagation();if(guide)return guide=0;if(my<565)return;if(my<600)zone=(zone+1)%3,S.s('ccZone',zone);else if(my<630)S.s('ccMode',mode=(mode+1)%4);else if(my<670)audio(),startLevel(train?0:1);else if(mx<W/2)train=!train;else guide=1}},true);
addEventListener('keydown',e=>{if(state==='title'&&e.code==='KeyC'){e.preventDefault();e.stopImmediatePropagation();guide=!guide;tone(260,.05,'triangle',.012,420);return}if(state==='title'&&guide){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Escape')guide=0;return}if(state==='title'&&e.code==='KeyT'){e.preventDefault();e.stopImmediatePropagation();train=!train;tone(260,.05,'triangle',.012,420);return}if(state==='title'&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(train?0:1);return}if(state==='play'&&!level&&intro.step===10&&e.code==='Enter'){e.preventDefault();e.stopImmediatePropagation();state='title';objs=[];return}if(state!=='play'||e.repeat)return;if(e.code.startsWith('Shift'))e.preventDefault(),e.stopImmediatePropagation(),cycle();else if(e.code==='Space')e.preventDefault(),e.stopImmediatePropagation(),dashSolo()},true);
addEventListener('keyup',e=>{if(state==='play'&&'WASD'.includes(e.code[3]))K[e.code]=0,e.stopImmediatePropagation()},true);
function crackWhip(){let w=whip,u=unis[w.i];if(!u||caps[0]!==w.i)return;let x=u.x-w.x,y=u.y-w.y,d=Math.hypot(x,y);if(d<32||d>210){w.hit=-1;return msg='MISS',msgT=.4}let c=u.tapT?u.tap+1:1,n=Math.min(5,(u.power|0)+1),a=Math.atan2(y,x);u.power=n;u.tap=c;u.tapT=.7;u.a=a;u.vx+=Math.cos(a)*(80+n*25);u.vy+=Math.sin(a)*(80+n*25);paintStamp(u,u.x,u.y,26+n*8);fx(u.x,u.y,4+n,85);tone(900+n*85,.035,'square',.03,180+n*35);tone(210+n*45,.055,'triangle',.018);msg=u.name+' • '+n+'/5';msgT=.45;if(c===2)award('2X WHIP',260);if(c>2){award('3X PRISM',700);paintStamp(u,u.x,u.y,92);for(let o of objs)if(o.hp>0&&Math.hypot(o.x+o.w/2-u.x,o.y+o.h/2-u.y)<150)hitObj(u,o,34*u.p.p);u.tap=0}if(!level&&n>1){if(intro.step===1)intro.o=caps[0],intro.step=2;if(intro.step===7&&caps[0]===intro.o)intro.step=8}w.hit=1}
const _soloHit=hitObj;hitObj=function(u,o,d){if(!level&&o&&o.lm==='bakery'){if(intro.step<8)return;let h=o.hp;_soloHit(u,o,d);if(h>0&&o.hp<=0)herdBurst();return}_soloHit(u,o,d)};
const _soloWorld=updateWorld;updateWorld=function(d){let a=unis[caps[0]],fast=[];for(let u of unis)if(u.live&&u!==a&&roadAt(u))u.p.sp*=1.1,fast.push(u);_soloWorld(d);for(let u of fast)u.p.sp/=1.1;for(let u of unis)if(u.live){if(u!==a&&(u.x<35||u.x>WW-35||u.y<35||u.y>WH-35)){u.order=1.5;u.ox=Math.sign(WW/2-u.x);u.oy=Math.sign(WH/2-u.y);u.vx+=u.ox*160;u.vy+=u.oy*160;u.distract=0}u===a?u.cool=0:u.cool=(u.cool||0)+d}};
function updateIntro(){if(level)return;let s=intro.step;if(!s&&intro.l)intro.step=1;else if(s===4&&intro.l){intro.step=5;let u=unis[intro.o];u.order=u.dash=u.rescue=0;u.distract=1.2;u.vx*=.2;u.vy*=.2;suggested=intro.o;if(flies[0])flies[0].x=u.x+28,flies[0].y=u.y+8}else if(s===6&&intro.rescue){intro.step=7}}
function herdBurst(){let o=LM[0].os[0];for(let i of[1,2,4,5])unis.push(makeUni(i,R(1100,100),R(560,100)));for(let u of unis){u.a=R(T);u.order=u.frenzy=0;u.anger=.35}o.hp=o.max=90;o.hue=85;o.lm=0;o.m=1;LM=[];stageGoal=2;intro.step=9;flash=.7;shake=12;msg='TOWN HALL GREW BACK!';msgT=2;tone(180,.3,'sawtooth',.04,760)}
const _soloUpdate=update;update=function(d){_soloUpdate(d);if(whip&&(whip.l-=d)<=0)whip=0};
introHud=function(){let m=['WASD • MOVE + PAINT','CLICK RING ×2 • CHARGE','SPACE • DASH','MOVE + SHIFT • SEND UNICORN','WASD • PAINT WITH NEW UNICORN','STUCK! • SHIFT BACK','WASD • PULL FREE','CLICK RING ×2 • RECHARGE','SPACE • SMASH BAKERY'],u=unis[caps[0]],o=objs.find(o=>o.m),n=o?team(o):0,s=intro.step<9?m[intro.step]:intro.step===9?n<3?'TO SMASH HALL → TEAM UP '+n+'/3':u.power<2?'TEAM 3/3 • CLICK RING ×2 • CHARGE':'TEAM 3/3 • SPACE • DASH → SMASH HALL':'READY • ENTER • MAIN TOWN';X.fillStyle='#05080fe6';if(intro.step===10){rr(W/2-360,H-128,720,106,14);X.fillStyle='#ffe77d';text('TUTORIAL COMPLETE • WHOLE TOWN PLAN',W/2,H-101,14,'center');X.fillStyle='#fff';text('BREAK 4 → BUILD CHAOS → TEAM UP AT HALL',W/2,H-76,14,'center');text('THEN PAINT 4 DISTRICTS + HIT COLOR GOAL',W/2,H-52,13,'center');text('3 CAPTURED = GAME OVER • ENTER = MENU',W/2,H-30,12,'center');return}rr(W/2-340,H-70,680,48,14);X.fillStyle='#ffe77d';text((intro.step+1)+'/10',W/2-310,H-42,11);X.fillStyle='#fff';text(s,W/2,H-42,15,'center')};
hud=function(){X.setTransform(1,0,0,1,0,0);if(!level)return introHud();let a=landWin===2?(victoryT>1?'TOWN HALL FALLS!':'RAINBOW TAKEOVER!'):landWin<0&&victoryT?(victoryT>1.5?'3 CAPTURED!':'HERD COLLAPSE!'):lmTextT>1?lmText:lmTextT?objective():msgT>.8?msg:'',c=cleaners.filter(q=>q.u>=0).length;if(!a&&!msgT&&!mode&&!plus&&!c){let u=unis[caps[0]],q=unis.filter(v=>v.live&&v!==u);if(q.length&&Math.min(...q.map(v=>v.cool||0))>11)a='TIP • SHIFT → CHECK HERD';else if(!u.power&&ups.some(p=>p.on)&&clock%16<1)a='TIP • AIM FOR POWER-UPS'}X.fillStyle='#05080fdb';rr(16,14,340,34,11);X.fillStyle='#fff';text(objective(),30,37,12);X.fillStyle='#05080fdb';rr(W-150,14,134,34,11);X.fillStyle=c>1?'#ff707b':'#fff';text(c>1?'DANGER '+c+'/3':'CAPTURED '+c+'/3',W-28,37,12,'right');if(a){X.fillStyle='#05080fe6';rr(W/2-190,18,380,36,12);X.fillStyle='#ffe56d';text(a,W/2,42,14,'center')}};
rules=function(){X.fillStyle='#112';X.fillRect(0,0,W,H);X.fillStyle='#fff';text('HOW TO PLAY',W/2,48,30,'center');X.font='12px Arial';['GOAL • MANAGE 6 • DESTROY + COLOR TOWN','WIN 1 • BREAK 4 LANDMARKS','WIN 2 • BUILD CHAOS = DAMAGE + PAINT','WIN 3 • TO SMASH HALL → TEAM UP','WIN 4 • PAINT 4 DISTRICTS + REACH COLOR GOAL','DISTRICTS = 4 MAP QUADRANTS • PAINT EACH','WASD • STEER ACTIVE UNICORN + PAINT','SHIFT • SWITCH • MOVE+SHIFT SENDS CURRENT UNICORN','SHIFT ×3 • SWEEP DIFFERENT HERD MEMBERS','TEAM X/Y • BRING Y UNICORNS CLOSE TO TARGET','CLICK RING ×2+ • CHARGE WHIP','SPACE • DASH • MORE CHARGE = LONGER','POWER-UPS • RUN INTO THEM','RAGE CORN • 7s FRENZY SMASH','PRISM POP • AREA PAINT + DAMAGE','RAINBOW SODA • 8s SPEED BOOST','CLEANERS • ERASE + SNATCH DISTRACTED HERD','RESCUE • HIT TRUCK + BRING 2 UNICORNS','3 CAPTURED = GAME OVER'].forEach((s,i)=>X.fillText(s,W/2,76+i*25));if(paused&&level)text('NOW • '+objective(),W/2,570,15,'center');text(paused?'P / ESC • RESUME':'C / ESC • BACK',W/2,650,14,'center')};
title=rules;
const _soloWorldDraw=world;world=function(){_soloWorldDraw();if(state!=='play')return;X.save();X.translate(ox,oy);X.scale(z,z);let u=unis[caps[0]],s=unis[suggested],n=u.power|0;X.strokeStyle='#fff';X.lineWidth=7+n;X.beginPath();X.arc(u.x,u.y,78+n*3,0,T);X.stroke();X.fillStyle='#fff';text((n>1?'DASH ':'WHIP ')+n+'/5',u.x,u.y-94-n*3,14,'center');let q=u.tapT?['','OW!','RUDE!','WHEE!','AGAIN?!','MAX!'][n]:!level&&(intro.step===1||intro.step===7&&caps[0]===intro.o)?'WHIP ME!':'';if(q)text(q,u.x,u.y-120-n*3,15,'center');if(!level&&intro.step===5&&s){X.fillStyle='#ffb7e8';text('▼ STUCK! • SHIFT',s.x,s.y-58,14,'center')}if(!level&&intro.step===8&&LM[0]&&LM[0].os[0]){let o=LM[0].os[0];X.fillStyle='#ffe77d';text('TARGET • BAKERY',o.x+o.w/2,o.y-48,15,'center')}if(!level&&intro.step===9){let o=objs.find(o=>o.m);X.fillStyle='#ffe77d';text('TOWN HALL • TEAM '+team(o)+'/3',o.x+o.w/2,o.y-48,15,'center')}if(whip){let q=unis[whip.i];if(q){let dx=q.x-whip.x,dy=q.y-whip.y,d=Math.hypot(dx,dy)||1,b=whip.l*520,cx=(whip.x+q.x)/2-dy/d*b,cy=(whip.y+q.y)/2+dx/d*b;X.lineCap='round';X.strokeStyle='#642';X.lineWidth=9;X.beginPath();X.moveTo(whip.x-dx/d*18,whip.y-dy/d*18);X.lineTo(whip.x,whip.y);X.stroke();for(let i=3;i--;){X.strokeStyle=`hsl(${clock*180+i*120} 100% 65%)`;X.lineWidth=4+i*3;X.beginPath();X.moveTo(whip.x,whip.y);X.quadraticCurveTo(cx,cy,q.x,q.y);X.stroke()}X.fillStyle='#fff';X.beginPath();X.arc(whip.x,whip.y,7,0,T);X.fill()}}X.restore()};
const _soloDraw=draw;draw=function(){_soloDraw();if(paused)return rules();X.save();X.translate(mx,my);for(let i=3;i--;){X.strokeStyle=`hsl(${clock*90+i*120} 100% 65%)`;X.lineWidth=4+i*3;X.beginPath();X.arc(-7,7,14+i*7,.2,5.6);X.stroke()}X.fillStyle='#fff';X.beginPath();X.arc(0,0,6,0,T);X.fill();X.restore()};
