let whip=0,suggested=-1,guide=0;
/* YELLOW: CLICK MALLOW RING */
function roadAt(u){if(!u||!PM)return 0;let x=cl(u.x/PS|0,0,PW-1),y=cl(u.y/PS|0,0,PH-1);return PM[y*PW+x]}
function bestIdle(){let j=-1,b=-1;for(let i=unis.length;i--;){let u=unis[i];if(u.live&&i!==caps[0]&&u.cool>b)b=u.cool,j=i}return j}
function nextLive(j=caps[0]){let o=j;do j=(j+1)%unis.length;while(!unis[j].live&&j!==o);return j}
const _soloStart=startLevel;startLevel=function(n){_soloStart(n);guide=0;caps=[0,-1];suggested=-1;if(!n)ups=[];if(n)for(let u of unis)u.live=1;for(let i=unis.length;i--;){let u=unis[i];u.power=0;u.cool=i/5;u.tap=u.tapT=0}};
capSide=i=>i===caps[0]?1:0;
const _soloAI=moveAI;moveAI=function(u,d){let c=caps[1];caps[1]=caps[0];let a=_soloAI(u,d);caps[1]=c;return a};
const _soloDistract=distractForce;distractForce=function(u){let f=_soloDistract(u);if(u!==unis[caps[0]]&&roadAt(u))f[0]*=.55,f[1]*=.55;return f};
cycle=function(){if(state!=='play')return;let o=caps[0],u=unis[o];if(Math.hypot(u.vx,u.vy)>35)u.order=roadAt(u)?5.2:4,u.ox=Math.cos(u.a),u.oy=Math.sin(u.a);if(level)dmask|=dmask&16?32:16;let j=nextLive(o);caps[0]=j;u=unis[j];u.order=u.cool=0;u.distract=Math.max(0,u.distract-.2);if(!level){if(intro.step===3&&j!==intro.o)intro.step=4,intro.l=0;else if(intro.step===5&&j===intro.o)intro.step=6,intro.rescue=0}msg='CONTROL → '+u.name;msgT=1};
const _soloWave=waveUp;waveUp=function(w){_soloWave(w);if(level)msg=w===2?'TOWN FIGHTS BACK':'FULL EMERGENCY',msgT=2};
function dashSolo(){if(state!=='play')return;let u=unis[caps[0]],n=u.power|0;if(n<2){msg='WHIP 2X → DASH';msgT=.7;return}u.dash=.2+n*.07;let v=570+n*95;u.vx=Math.cos(u.a)*v;u.vy=Math.sin(u.a)*v;paintStamp(u,u.x,u.y,38+n*12);fx(u.x,u.y,6+n*2,120);tone(150+n*35,.1,'sawtooth',.03);u.power=u.tap=u.tapT=0;if(n===5)award('MAX DASH',850);if(!level&&intro.step===2){intro.step=3;msg='SHIFT → SWITCH';msgT=1}else if(!level&&intro.step===8){msg='SMASH THE BAKERY!';msgT=.7}}
C.addEventListener('mousedown',e=>{if(state!=='play'||e.button)return;e.preventDefault();e.stopImmediatePropagation();audio();if(!level&&intro.step<7&&intro.step!==1){msg=intro.step?'FOLLOW LESSON':'MOVE FIRST';msgT=.5;return}let u=unis[caps[0]],x=(mx-ox)/z,y=(my-oy)/z,d=Math.hypot(x-u.x,y-u.y);if(d>38&&d<180)whip={x,y,i:caps[0],l:.13,hit:0},crackWhip();else msg='CLICK WHITE RING',msgT=.5},true);
C.addEventListener('mousedown',e=>{if(state==='title'){e.preventDefault();e.stopImmediatePropagation();if(!guide)audio(),startLevel(S.g('ccIntro16')?1:0)}},true);
addEventListener('keydown',e=>{if(state==='title'&&e.code==='KeyC'){e.preventDefault();e.stopImmediatePropagation();guide=!guide;tone(260,.05,'triangle',.012,420);return}if(state==='title'&&guide){e.preventDefault();e.stopImmediatePropagation();if(e.code==='Escape')guide=0;return}if(state==='title'&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(S.g('ccIntro16')?1:0);return}if(state!=='play'||e.repeat)return;if(e.code.startsWith('Shift'))e.preventDefault(),e.stopImmediatePropagation(),cycle();else if(e.code==='Space')e.preventDefault(),e.stopImmediatePropagation(),dashSolo()},true);
addEventListener('keyup',e=>{if(state==='play'&&'WASD'.includes(e.code[3]))K[e.code]=0,e.stopImmediatePropagation()},true);
function crackWhip(){let w=whip,u=unis[w.i];if(!u||caps[0]!==w.i)return;let x=u.x-w.x,y=u.y-w.y,d=Math.hypot(x,y);if(d<32||d>210){w.hit=-1;return msg='MISS',msgT=.4}let c=u.tapT?u.tap+1:1,n=Math.min(5,(u.power|0)+1),a=Math.atan2(y,x);u.power=n;u.tap=c;u.tapT=.7;u.a=a;u.vx+=Math.cos(a)*(80+n*25);u.vy+=Math.sin(a)*(80+n*25);paintStamp(u,u.x,u.y,26+n*8);fx(u.x,u.y,4+n,85);tone(900+n*85,.035,'square',.03,180+n*35);tone(210+n*45,.055,'triangle',.018);msg=u.name+' • '+n+'/5';msgT=.45;if(c===2)award('2X WHIP',260);if(c>2){award('3X PRISM',700);paintStamp(u,u.x,u.y,92);for(let o of objs)if(o.hp>0&&Math.hypot(o.x+o.w/2-u.x,o.y+o.h/2-u.y)<150)hitObj(u,o,34*u.p.p);u.tap=0}if(!level&&n===2){if(intro.step===1)intro.o=caps[0],intro.step=2;if(intro.step===7&&caps[0]===intro.o)intro.step=8}w.hit=1}
const _soloHit=hitObj;hitObj=function(u,o,d){if(!level&&o&&o.lm==='bakery'){if(intro.step<8)return;let h=o.hp;_soloHit(u,o,d);if(h>0&&o.hp<=0)herdBurst();return}_soloHit(u,o,d)};
const _soloWorld=updateWorld;updateWorld=function(d){let a=unis[caps[0]],fast=[];for(let u of unis)if(u.live&&u!==a&&roadAt(u))u.p.sp*=1.1,fast.push(u);_soloWorld(d);for(let u of fast)u.p.sp/=1.1;for(let u of unis)if(u.live){if(u!==a&&(u.x<35||u.x>WW-35||u.y<35||u.y>WH-35)){u.order=1.5;u.ox=Math.sign(WW/2-u.x);u.oy=Math.sign(WH/2-u.y);u.vx+=u.ox*160;u.vy+=u.oy*160;u.distract=0}u===a?u.cool=0:u.cool=(u.cool||0)+d*(u.order||u.frenzy||u.boost?.2:Math.hypot(u.vx,u.vy)<75?1.8:1)}suggested=!level&&intro.step===5?intro.o:bestIdle()};
function updateIntro(){if(level)return;let s=intro.step;if(!s&&intro.l)intro.step=1;else if(s===4&&intro.l){intro.step=5;let u=unis[intro.o];u.order=u.dash=u.rescue=0;u.distract=1.2;u.vx*=.2;u.vy*=.2;suggested=intro.o;if(flies[0])flies[0].x=u.x+28,flies[0].y=u.y+8;msg=u.name+' IS STUCK • SHIFT';msgT=1.4}else if(s===6&&intro.rescue){intro.step=7;msg='FREE! • CLICK RING ×2';msgT=1}}
function herdBurst(){for(let i of[1,2,4,5])unis.push(makeUni(i,R(1100,100),R(560,100)));for(let u of unis){u.a=R(T);u.order=2.4;u.ox=Math.cos(u.a);u.oy=Math.sin(u.a);u.anger=1;u.frenzy=2.2}LM=[];stageGoal=2;intro.step=9;intro.l=5;flash=.7;shake=12;msg='ALL SIX!';msgT=2;tone(180,.3,'sawtooth',.04,760)}
const _soloUpdate=update;update=function(d){_soloUpdate(d);if(!level&&intro.step===9&&(intro.l-=d)<=0){S.s('ccIntro16',1);startLevel(1);msg='SIX UNICORNS • BIG TOWN';msgT=2}if(whip&&(whip.l-=d)<=0)whip=0};
introHud=function(){let m=['WASD • MOVE ACTIVE','CLICK WHITE RING ×2','SPACE • DASH','SHIFT • SWITCH UNICORN','WASD • PAINT WITH NEW UNICORN','STUCK UNICORN • SHIFT','WASD • PULL THEM FREE','CLICK WHITE RING ×2','SPACE • SMASH BAKERY','SHIFT • WHIP • DASH • GO WILD'],h=['WHITE RING = YOU','2 WHIPS = DASH • 5 = MAX','MORE WHIPS = LONGER DASH','SHIFT ANY TIME • OLD KEEPS RUNNING','RAINBOW ROADS HELP HERD','NEXT SHOWS WHO NEEDS YOU','MOVING BREAKS DISTRACTION','2 WHIPS = DASH • 5 = MAX','DASH BREAKS LANDMARKS','ALL SIX ARE LIVE'];X.fillStyle='rgba(5,8,15,.9)';rr(W/2-340,H-82,680,64,16);X.fillStyle='#ffe77d';text((intro.step+1)+'/10',W/2-310,H-52,11);X.fillStyle='#fff';text(m[intro.step],W/2,H-55,15,'center');X.fillStyle='#b8c7dc';text(h[intro.step],W/2,H-34,10,'center')};
hud=function(){X.setTransform(1,0,0,1,0,0);if(!level)return introHud();let n=LM.slice(0,-1).filter(lmDone).length,u=unis[caps[0]],s=unis[suggested],h=hallDone(),g=h?stageGoal:chaos(),p=h?paintPct():takeover();X.fillStyle='rgba(5,8,15,.88)';rr(18,16,W-36,48,14);X.fillStyle='#fff';text(n<4?'BREAK '+n+'/4':p<g?(h?'COLOR ':'PAINT • CHAOS ')+(p*100|0)+'/'+(g*100|0):h&&(dmask&15)<15?'SPREAD 4':h?'HOLD':'HALL READY',34,46,13);text('YOU '+u.name+' • '+(u.power>1?'DASH ':'WHIP ')+(u.power|0)+'/5'+(s?' • NEXT '+s.name:''),W/2,46,13,'center');text(timeLeft.toFixed(1)+'s',W-34,46,13,'right');text('SHIFT = RESCUE • NEXT = NEEDS YOU • PAINT = HIGHWAY',W/2,H-14,11,'center')};
title=function(){X.fillStyle='#10142d';X.fillRect(0,0,W,H);X.fillStyle='#fff';if(guide){text('CONTROLS',W/2,95,42,'center');text('BIG WHITE RING = YOU',W/2,155,16,'center');text('WASD • MOVE + PAINT',W/2,220,15,'center');text('RAINBOW WHIP • CLICK BESIDE RING',W/2,260,14,'center');text('WHIP 2–5× • MORE = LONGER DASH',W/2,300,14,'center');text('SPACE • DASH AT 2+',W/2,340,14,'center');text('SHIFT • SWITCH ANY TIME • OLD KEEPS RUNNING',W/2,380,14,'center');X.fillStyle='#ffe77d';text('RULES',W/2,445,18,'center');X.fillStyle='#fff';text('PAINT = HIGHWAY FOR AUTONOMOUS UNICORNS',W/2,485,13,'center');text('NEXT = DISTRACTED / STALLED',W/2,520,13,'center');text('BREAK 4 + 28%+ CHAOS → TOWN HALL',W/2,555,14,'center');text('C / ESC • BACK',W/2,625,14,'center')}else{text('UNICORN STAMPEDE',W/2,185,52,'center');text('CONTROL THE HERD',W/2,275,20,'center');text(S.g('ccIntro16')?'ENTER • PLAY':'ENTER • TRAINING',W/2,390,20,'center');text('C • CONTROLS',W/2,430,14,'center')}};
const _soloWorldDraw=world;world=function(){_soloWorldDraw();if(state!=='play')return;X.save();X.translate(ox,oy);X.scale(z,z);let u=unis[caps[0]],s=unis[suggested],v=unis[nextLive()],n=u.power|0;X.strokeStyle='#fff';X.lineWidth=7+n;X.beginPath();X.arc(u.x,u.y,78+n*3,0,T);X.stroke();X.fillStyle='#fff';text((n>1?'DASH ':'WHIP ')+n+'/5',u.x,u.y-94-n*3,14,'center');X.fillStyle='#dff7ff';text('SHIFT → '+v.name,u.x,u.y+108,11,'center');let q=u.tapT?['','OW!','RUDE!','WHEE!','AGAIN?!','MAX!'][n]:!level&&(intro.step===1||intro.step===9||intro.step===7&&caps[0]===intro.o)?'WHIP ME!':'';if(q)text(q,u.x,u.y-120-n*3,15,'center');if(level&&s&&s.cool>1.5){X.fillStyle='#ffb7e8';text('NEXT',s.x,s.y-55,12,'center')}if(!level&&intro.step===5&&s){X.fillStyle='#ffb7e8';text('▼ STUCK! • SHIFT',s.x,s.y-58,14,'center')}if(!level&&intro.step===8&&LM[0]&&LM[0].os[0]){let o=LM[0].os[0];X.fillStyle='#ffe77d';text('TARGET • BAKERY',o.x+o.w/2,o.y-48,15,'center')}if(whip){let q=unis[whip.i];if(q){let dx=q.x-whip.x,dy=q.y-whip.y,d=Math.hypot(dx,dy)||1,b=whip.l*520,cx=(whip.x+q.x)/2-dy/d*b,cy=(whip.y+q.y)/2+dx/d*b;X.lineCap='round';X.strokeStyle='#642';X.lineWidth=9;X.beginPath();X.moveTo(whip.x-dx/d*18,whip.y-dy/d*18);X.lineTo(whip.x,whip.y);X.stroke();for(let i=3;i--;){X.strokeStyle=`hsl(${clock*180+i*120} 100% 65%)`;X.lineWidth=3+i*3;X.beginPath();X.moveTo(whip.x,whip.y);X.quadraticCurveTo(cx,cy,q.x,q.y);X.stroke()}X.fillStyle='#fff';X.beginPath();X.arc(whip.x,whip.y,7,0,T);X.fill()}}X.restore()};
const _soloDraw=draw;draw=function(){_soloDraw();X.save();X.translate(mx,my);for(let i=3;i--;){X.strokeStyle=`hsl(${clock*90+i*120} 100% 65%)`;X.lineWidth=4+i*3;X.beginPath();X.arc(-7,7,14+i*7,.2,5.6);X.stroke()}X.fillStyle='#fff';X.beginPath();X.arc(0,0,6,0,T);X.fill();X.restore()};
