let zone=S.g('ccZone')%3,runN=S.g('ccRun'),seedZone=0,wind=1,windT=0,chains=0,N='CANDY STORE,YACHT CLUB,SURF SHOP,BOATHOUSE,BAIT SHOP,BAKERY,BANK,BOOKS,CAFE,FLORIST,MARKET,TOYS,ARCADE,BAIT,DOCK,FISH,FERRY,FARMERS,STARTUP,YOGA,CAFE,PRISMBOROUGH,WASHWATER BAY,CLOUDTOP HEIGHTS'.split(',');
const _rain=paintStamp;paintStamp=(u,x=u.x,y=u.y,r=28)=>_rain(u,x,y,r+(level?stamp:0));
const _day=today;today=()=>_day()+seedZone*173+runN*19;
function grade(){let p=paintPct()>stageGoal+.07;return landWin?1+p+(p&&chains>[1,1,2][zone]):0}
function finishZone(){let c=grade(),k='ccC'+zone;if(c>S.g(k))S.s(k,c)}
function harbor(){roads.splice(1,1);roads[0][2]=140;roads[1][2]=160;let h=objs.filter(o=>o.t==='hedge'),a=[0,270,730,930,1320,1560],x=[1380,1450,1510,1470,1400,1340];for(let i=6;i--;)h[i].x=x[i],h[i].y=a[i],h[i].w=220,h[i].h=i<2?270:i<4?200:240;cars=cars.filter(c=>c.dir||c.x<1200||c.x>2e3);ups[2].x=ups[6].x=1630;ups[2].y=630;ups[6].y=1225;a=[N[0],N[4],N[2],'HARBOR CLOCK',N[1]];for(let i=5;i--;)for(let o of LM[i].os)o.ln=LM[i].n=a[i];objs.find(o=>o.t==='pond').ln='MARINA';flowers=[];objs=objs.filter(o=>o.t!=='fountain')}
function heights(){roads.splice(3);let h=objs.filter(o=>o.t==='hedge');for(let i=6;i--;)h[i].x=400+i*460,h[i].y=(i&1)*800,h[i].w=70,h[i].h=1e3;cars=cars.filter(c=>!c.dir);objs.find(o=>o.t==='clock').x=1e3;for(let o of objs)if(o.t==='stall')o.x+=80;ups[2].x=1900;ups[5].x=800;ups[2].y=ups[5].y=700;flowers=[];flies=[];objs=objs.filter(o=>o.t!=='fountain'&&o.t!=='pond')}
addEventListener('keydown',e=>{if(state==='title'&&(e.code==='KeyA'||e.code==='KeyD')){zone=(zone+(e.code==='KeyD'?1:2))%3;S.s('ccZone',zone);tone(280,.05,'triangle',.012,420)}});
const _startW=startLevel;startLevel=function(n){seedZone=n?zone:0;if(n)S.s('ccRun',++runN);_startW(n);if(n&&zone)zone>1?heights():harbor();let i=0;for(let o of objs)if(o.t==='b')o.k=o.lm==='bakery'?0:1+i++%7;wind=1;windT=2;chains=0;if(n){if(zone===1){addClean(mode?2:1);for(let c of cleaners)c.v*=mode?1.35:1.08}lmText=N[21+zone];lmTextT=2}};
const _crackW=crackWhip;crackWhip=function(){let u=unis[whip.i],n=u&&u.tapT?u.tap+1:1;_crackW();if(whip&&whip.hit>0){u=unis[whip.i];if(n>2)chains++;if(zone===2&&level&&u){u.tapT=Math.min(u.tapT,.5);u.vx*=1.14;u.vy*=1.14}}};
function updateZone(dt){if(!level||zone!==2)return;windT-=dt;if(windT<=0){windT=4;wind*=-1;lmText=wind>0?'CROSSWIND →':'← CROSSWIND';lmTextT=1}for(let u of unis)if(u.live)u.vx+=wind*((mode?90:58)+stamp*8)*dt}
const _updateW=update;update=function(dt){let before=state;_updateW(dt);if(state==='play'&&!paused)updateZone(dt);if(before==='play'&&state==='end')finishZone()};
const _titleW=title;
